### ISSUE TITLE
Limitar tamanho do container de postagens

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-web-old#11]
# Qual é o comportamento esperado?
Uma postagem com uma mensagem longa não deveria ultrapassar a largura máxima da tela.

# Qual é o comportamento atual?
![image](https://user-images.githubusercontent.com/12667933/146827019-ac40de03-03f7-4bc3-a6be-c15b1935bcb3.png)
![image](https://user-images.githubusercontent.com/12667933/146827010-49d15081-71ee-4fda-b479-ef513752df9f.png)

# Estou vendo esse comportamento em

- Android

## Versão do OS
Android 11

# Como eu posso reproduzir isso?
Criando uma postagem com uma mensagem extensa.

# Informações Adicionais
—

**Comment by DanielSalis** [comment]
@dsalexan Mano, acho que só consegui reproduzir esse erro no devtools selecionando o iphone 5/Se. Aí ocorre que o body inteiro não obedece o valor de 100% no width da página

**Comment by DanielSalis** [comment]
Acredito que foi resolvido nessa [issue](https://github.com/UnifespCodeLab/plasmedis-web/issues/6)
